services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: "msg-broker"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER = msg_queue
      - RABBITMQ_DEFAULT_PASS = broker123
    restart: always


